# -*- coding: utf-8 -*-
"""task02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgu4w98JZIzfad-DB88j_9AVhfBltgsp
"""

# Project 2: Exploratory Data Analysis (EDA)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

# 1. LOAD DATA

from google.colab import files
uploaded = files.upload()
df = pd.read_excel("Dataset for Data Analytics.xlsx")

print("Shape:", df.shape)
print(df.info())
print(df.head())

# 2. DESCRIPTIVE STATISTICS (mean, median, count)
numeric_cols = ["Quantity", "UnitPrice", "ItemsInCart", "TotalPrice"]

print("\n=== Numeric summary ===")
print(df[numeric_cols].describe())

print("\n=== Median (separately, since describe() only gives 50%) ===")
print(df[numeric_cols].median())

print("\n=== Categorical summary ===")
print(df.describe(include="object"))

print("\n=== Missing values ===")
print(df.isnull().sum())

# 3. UNIVARIATE ANALYSIS - DISTRIBUTIONS
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
for ax, col in zip(axes.flatten(), numeric_cols):
    sns.histplot(df[col], kde=True, ax=ax, color="steelblue")
    ax.set_title(f"Distribution of {col}")
plt.tight_layout()
plt.savefig("distributions.png", dpi=150)
plt.show()

# 4. OUTLIER DETECTION (IQR method) + Boxplots

fig, axes = plt.subplots(1, 4, figsize=(18, 5))
outlier_summary = {}

for ax, col in zip(axes, numeric_cols):
    sns.boxplot(y=df[col], ax=ax, color="lightcoral")
    ax.set_title(col)

    q1, q3 = df[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    low, high = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    outliers = df[(df[col] < low) | (df[col] > high)]
    outlier_summary[col] = len(outliers)

plt.tight_layout()
plt.savefig("boxplots.png", dpi=150)
plt.show()

print("\n=== Outlier counts (IQR method) ===")
print(outlier_summary)

# Inspect the TotalPrice outliers directly
q1, q3 = df["TotalPrice"].quantile([0.25, 0.75])
iqr = q3 - q1
high = q3 + 1.5 * iqr
print("\nTotalPrice outliers (high-value orders):")
print(df[df["TotalPrice"] > high][
    ["OrderID", "Product", "Quantity", "UnitPrice", "TotalPrice", "OrderStatus"]
])

# 5. TREND ANALYSIS - Orders & Revenue over time
df["YearMonth"] = df["Date"].dt.to_period("M").astype(str)
monthly = (
    df.groupby("YearMonth")
    .agg(orders=("OrderID", "count"), revenue=("TotalPrice", "sum"))
    .reset_index()
)

fig, ax1 = plt.subplots(figsize=(14, 6))
ax2 = ax1.twinx()
ax1.bar(monthly["YearMonth"], monthly["orders"], color="steelblue", alpha=0.6, label="Orders")
ax2.plot(monthly["YearMonth"], monthly["revenue"], color="darkorange", marker="o", label="Revenue")
ax1.set_xticks(range(len(monthly)))
ax1.set_xticklabels(monthly["YearMonth"], rotation=90)
ax1.set_ylabel("Orders")
ax2.set_ylabel("Revenue ($)")
ax1.set_title("Monthly Orders & Revenue Trend")
plt.tight_layout()
plt.savefig("monthly_trend.png", dpi=150)
plt.show()

print("\nPeak month:\n", monthly.loc[monthly["revenue"].idxmax()])
print("\nLowest month:\n", monthly.loc[monthly["revenue"].idxmin()])

# 6. CATEGORICAL BREAKDOWN - order counts
categorical_cols = ["Product", "PaymentMethod", "OrderStatus", "ReferralSource"]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
for ax, col in zip(axes.flatten(), categorical_cols):
    df[col].value_counts().plot(kind="bar", ax=ax, color="teal")
    ax.set_title(f"Order Count by {col}")
plt.tight_layout()
plt.savefig("categorical_breakdown.png", dpi=150)
plt.show()

# 7. REVENUE BY CATEGORY (bivariate: category vs TotalPrice)
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
for ax, col in zip(axes.flatten(), categorical_cols):
    df.groupby(col)["TotalPrice"].sum().sort_values(ascending=False).plot(
        kind="bar", ax=ax, color="pink"
    )
    ax.set_title(f"Total Revenue by {col}")
plt.tight_layout()
plt.savefig("revenue_breakdown.png", dpi=150)
plt.show()

# 8. CORRELATION ANALYSIS

corr = df[numeric_cols].corr()
plt.figure(figsize=(6, 5))
sns.heatmap(corr, annot=True, cmap="coolwarm", center=0, vmin=-1, vmax=1)
plt.title("Correlation Matrix")
plt.tight_layout()
plt.savefig("correlation_heatmap.png", dpi=150)
plt.show()

print("\n=== Correlation matrix ===")
print(corr)

# 9. KEY OBSERVATIONS

cancel_return_rate = df["OrderStatus"].isin(["Cancelled", "Returned"]).mean() * 100

print("\n===== KEY OBSERVATIONS =====")
print(f"Total orders: {len(df)}")
print(f"Date range: {df['Date'].min().date()} to {df['Date'].max().date()}")
print(f"Total revenue: ${df['TotalPrice'].sum():,.2f}")
print(f"Mean order value: ${df['TotalPrice'].mean():,.2f} | Median: ${df['TotalPrice'].median():,.2f}")
print(f"Cancelled + Returned rate: {cancel_return_rate:.1f}%")
print(f"Strongest correlation: UnitPrice <-> TotalPrice (r = {corr.loc['UnitPrice','TotalPrice']:.2f})")